In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
dataset = pd.read_csv("loan-train.csv")

In [3]:
dataset.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [4]:
dataset.shape

(614, 13)

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             601 non-null    object
 2   Married            611 non-null    object
 3   Dependents         599 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      582 non-null    object
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object
 12  Loan_Status        614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB

In [6]:
dataset.describe()

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,614.000000,614.000000,592.000000,600.00000,564.000000
mean,5403.459283,1621.245798,146.412162,342.00000,0.842199
std,6109.041673,2926.248369,85.587325,65.12041,0.364878
min,150.000000,0.000000,9.000000,12.00000,0.000000
25%,2877.500000,0.000000,100.000000,360.00000,1.000000
50%,3812.500000,1188.500000,128.000000,360.00000,1.000000
75%,5795.000000,2297.250000,168.000000,360.00000,1.000000
max,81000.000000,41667.000000,700.000000,480.00000,1.000000

In [7]:
pd.crosstab(dataset['Credit_History'],dataset['Loan_Status'], margins=True)

Loan_Status       N    Y  All
Credit_History
0.0              82    7   89
1.0              97  378  475
All             179  385  564

In [8]:
dataset.boxplot(column='ApplicantIncome')

In [9]:
dataset['ApplicantIncome'].hist(bins=20)

In [10]:
dataset['CoapplicantIncome'].hist(bins=20)

In [11]:
dataset.boxplot(column='ApplicantIncome', xlabel='Education')

In [12]:
dataset.boxplot(column='LoanAmount')

In [13]:
dataset['LoanAmount'].hist(bins=20)

In [14]:
dataset['LoanAmount_log']=np.log(dataset['LoanAmount'])
dataset['LoanAmount_log'].hist(bins=20)

In [15]:
dataset.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
LoanAmount_log       22
dtype: int64

In [16]:
dataset['Gender'].fillna(dataset['Gender'].mode()[0],inplace=True)

C:\Users\hp\AppData\Local\Temp\ipykernel_5060\2782724874.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Gender'].fillna(dataset['Gender'].mode()[0],inplace=True)

In [17]:
dataset['Married'].fillna(dataset['Married'].mode()[0],inplace=True)

C:\Users\hp\AppData\Local\Temp\ipykernel_5060\568568310.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Married'].fillna(dataset['Married'].mode()[0],inplace=True)

In [18]:
dataset['Dependents'].fillna(dataset['Dependents'].mode()[0],inplace=True)

C:\Users\hp\AppData\Local\Temp\ipykernel_5060\2291896846.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Dependents'].fillna(dataset['Dependents'].mode()[0],inplace=True)

In [19]:
dataset['Self_Employed'].fillna(dataset['Self_Employed'].mode()[0],inplace=True)

C:\Users\hp\AppData\Local\Temp\ipykernel_5060\39551059.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Self_Employed'].fillna(dataset['Self_Employed'].mode()[0],inplace=True)

In [20]:
dataset.LoanAmount = dataset.LoanAmount.fillna(dataset.LoanAmount.mean())
dataset.LoanAmount_log = dataset.LoanAmount_log.fillna(dataset.LoanAmount_log.mean())

In [21]:
dataset['Loan_Amount_Term'].fillna(dataset['Loan_Amount_Term'].mode()[0],inplace=True)

C:\Users\hp\AppData\Local\Temp\ipykernel_5060\3879141361.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Loan_Amount_Term'].fillna(dataset['Loan_Amount_Term'].mode()[0],inplace=True)

In [22]:
dataset['Credit_History'].fillna(dataset['Credit_History'].mode()[0],inplace=True)

C:\Users\hp\AppData\Local\Temp\ipykernel_5060\979352118.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Credit_History'].fillna(dataset['Credit_History'].mode()[0],inplace=True)

In [23]:
dataset.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
LoanAmount_log       0
dtype: int64

In [24]:
dataset['TotalIncome']= dataset['ApplicantIncome'] = dataset['CoapplicantIncome']
dataset['TotalIncome_log']= np.log(dataset['TotalIncome'])

C:\ProgramData\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

In [25]:
import numpy as np

# Replace 0 or negative values with NaN before log
dataset['TotalIncome'] = dataset['TotalIncome'].replace(0, np.nan)

# Apply log
dataset['TotalIncome_log'] = np.log(dataset['TotalIncome'])

# Drop rows with NaN or Inf values
dataset = dataset.replace([np.inf, -np.inf], np.nan)
dataset = dataset.dropna(subset=['TotalIncome_log'])

# Now plot
dataset['TotalIncome_log'].hist(bins=20)

In [26]:
dataset.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,LoanAmount_log,TotalIncome,TotalIncome_log
1,LP001003,Male,Yes,1,Graduate,No,1508.0,1508.0,128.0,360.0,1.0,Rural,N,4.852030,1508.0,7.318540
3,LP001006,Male,Yes,0,Not Graduate,No,2358.0,2358.0,120.0,360.0,1.0,Urban,Y,4.787492,2358.0,7.765569
5,LP001011,Male,Yes,2,Graduate,Yes,4196.0,4196.0,267.0,360.0,1.0,Urban,Y,5.587249,4196.0,8.341887
6,LP001013,Male,Yes,0,Not Graduate,No,1516.0,1516.0,95.0,360.0,1.0,Urban,Y,4.553877,1516.0,7.323831
7,LP001014,Male,Yes,3+,Graduate,No,2504.0,2504.0,158.0,360.0,0.0,Semiurban,N,5.062595,2504.0,7.825645

In [27]:
X= dataset.iloc[:,np.r_[1:5,9:11,13:15]].values
Y= dataset.iloc[:,12].values

In [28]:
X

array([['Male', 'Yes', '1', ..., 1.0, 4.852030263919617, 1508.0],
       ['Male', 'Yes', '0', ..., 1.0, 4.787491742782046, 2358.0],
       ['Male', 'Yes', '2', ..., 1.0, 5.58724865840025, 4196.0],
       ...,
       ['Male', 'Yes', '2', ..., 1.0, 5.056245805348308, 1411.0],
       ['Male', 'Yes', '0', ..., 1.0, 4.68213122712422, 1950.0],
       ['Male', 'Yes', '1', ..., 1.0, 5.53338948872752, 240.0]],
      dtype=object)

In [29]:
Y

array(['N', 'Y', 'Y', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'N', 'Y', 'Y',
       'Y', 'N', 'N', 'N', 'Y', 'Y', 'Y', 'N', 'Y', 'N', 'Y', 'N', 'Y',
       'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y',
       'N', 'N', 'N', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'Y', 'N', 'N', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'Y', 'N', 'Y', 'Y', 'N', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y',
       'N', 'N', 'Y', 'N', 'Y', 'N', 'N', 'Y', 'Y', 'Y', 'N', 'Y', 'Y',
       'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'N',
       'N', 'N', 'N', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'N', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'N', 'Y', 'Y', 'N',
       'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y',
       'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'Y',
       'Y', 'Y', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N',
       'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'N', 'Y',
       'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'N', 'Y',
       'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'Y', 'Y', 'N', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N',
       'Y', 'N', 'Y', 'N', 'Y', 'Y', 'N', 'Y', 'N', 'Y', 'N', 'Y', 'Y',
       'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y',
       'N', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'N', 'N',
       'Y', 'Y', 'N', 'N', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y',
       'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'N', 'N', 'Y', 'N', 'Y', 'Y',
       'Y', 'N', 'N', 'N', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'Y', 'N', 'Y',
       'Y', 'Y', 'Y'], dtype=object)

In [30]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2, random_state=0)

In [31]:
print(X_train)

[['Male' 'No' '0' ... 1.0 4.007333185232471 2531.0]
 ['Male' 'Yes' '2' ... 1.0 5.41610040220442 1126.0]
 ['Male' 'Yes' '0' ... 1.0 4.812184355372417 4417.0]
 ...
 ['Male' 'Yes' '3+' ... 0.0 4.852030263919617 1250.0]
 ['Male' 'Yes' '3+' ... 0.0 5.19295685089021 4000.0]
 ['Female' 'No' '0' ... 0.0 4.6443908991413725 1863.0]]

In [32]:
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()

In [33]:
for i in range(0,5):
    X_train[:,i]= labelencoder_X.fit_transform(X_train[:,i])

In [34]:
X_train[:,7]= labelencoder_X.fit_transform(X_train[:,7])

In [35]:
X_train

array([[1, 0, 0, ..., 1.0, 4.007333185232471, 149],
       [1, 1, 2, ..., 1.0, 5.41610040220442, 21],
       [1, 1, 0, ..., 1.0, 4.812184355372417, 209],
       ...,
       [1, 1, 3, ..., 0.0, 4.852030263919617, 27],
       [1, 1, 3, ..., 0.0, 5.19295685089021, 198],
       [0, 0, 0, ..., 0.0, 4.6443908991413725, 90]], dtype=object)

In [36]:
labelencoder_Y=LabelEncoder()
Y_train= labelencoder_Y.fit_transform(Y_train)

In [37]:
Y_train

array([1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0])

In [38]:
for i in range(0,5):
    X_test[:,i]= labelencoder_X.fit_transform(X_test[:,i])

In [39]:
X_test[:,7]= labelencoder_X.fit_transform(X_test[:,7])

In [40]:
labelencoder_Y=LabelEncoder()
Y_test= labelencoder_Y.fit_transform(Y_test)

In [41]:
X_test

array([[1, 1, 0, 0, 4, 1.0, 5.19295685089021, 36],
       [1, 1, 0, 0, 4, 1.0, 4.7535901911063645, 21],
       [1, 1, 2, 0, 2, 1.0, 5.236441962829949, 59],
       [1, 1, 2, 1, 4, 0.0, 4.718498871295094, 20],
       [1, 1, 0, 0, 4, 1.0, 4.9344739331306915, 34],
       [1, 1, 0, 0, 4, 1.0, 5.375278407684165, 56],
       [1, 1, 1, 0, 4, 1.0, 5.062595033026967, 46],
       [1, 1, 0, 0, 4, 1.0, 4.875197323201151, 49],
       [1, 1, 2, 0, 4, 1.0, 5.0106352940962555, 7],
       [1, 1, 2, 0, 4, 1.0, 5.493061443340548, 54],
       [1, 0, 3, 1, 4, 1.0, 4.997212273764115, 22],
       [1, 0, 0, 0, 4, 1.0, 4.204692619390966, 55],
       [1, 1, 2, 0, 4, 1.0, 4.997212273764115, 27],
       [1, 1, 0, 0, 4, 1.0, 5.075173815233827, 3],
       [1, 1, 0, 0, 4, 1.0, 4.867534450455582, 32],
       [1, 1, 1, 0, 4, 1.0, 5.855071922202427, 65],
       [1, 1, 0, 0, 4, 1.0, 5.1647859739235145, 52],
       [1, 1, 0, 0, 2, 1.0, 4.248495242049359, 61],
       [1, 1, 3, 0, 4, 1.0, 4.553876891600541, 28],
       [1, 1, 1, 0, 4, 1.0, 5.53338948872752, 0],
       [1, 1, 0, 0, 4, 1.0, 4.477336814478207, 30],
       [1, 0, 0, 0, 2, 1.0, 4.787491742782046, 53],
       [1, 1, 1, 0, 4, 1.0, 4.727387818712341, 42],
       [1, 1, 0, 0, 4, 1.0, 5.541263545158426, 58],
       [1, 1, 1, 0, 4, 1.0, 5.303304908059076, 47],
       [1, 1, 3, 1, 5, 1.0, 4.543294782270004, 3],
       [1, 1, 0, 0, 0, 1.0, 4.709530201312334, 38],
       [1, 0, 0, 0, 4, 1.0, 5.214935757608986, 63],
       [1, 1, 2, 0, 2, 1.0, 4.356708826689592, 5],
       [0, 1, 0, 0, 4, 1.0, 4.867534450455582, 1],
       [1, 1, 2, 0, 4, 1.0, 4.248495242049359, 2],
       [1, 1, 2, 1, 4, 1.0, 4.969813299576001, 39],
       [1, 1, 0, 0, 4, 1.0, 4.8283137373023015, 4],
       [1, 1, 2, 1, 4, 1.0, 4.59511985013459, 23],
       [0, 0, 0, 0, 3, 1.0, 4.59511985013459, 15],
       [1, 1, 2, 1, 2, 1.0, 4.727387818712341, 12],
       [1, 1, 2, 0, 4, 1.0, 5.0106352940962555, 11],
       [1, 0, 0, 0, 4, 1.0, 5.017279836814924, 48],
       [1, 1, 2, 0, 4, 1.0, 5.10594547390058, 45],
       [1, 1, 0, 0, 4, 1.0, 5.717027701406222, 29],
       [1, 0, 0, 0, 4, 1.0, 4.48863636973214, 44],
       [1, 1, 2, 0, 4, 1.0, 5.337538079701318, 57],
       [1, 0, 0, 0, 4, 1.0, 5.220355825078324, 19],
       [1, 0, 0, 0, 4, 1.0, 4.941642422609304, 35],
       [1, 1, 0, 0, 4, 0.0, 4.912654885736052, 31],
       [0, 1, 2, 0, 5, 1.0, 4.727387818712341, 13],
       [1, 1, 0, 0, 4, 1.0, 3.912023005428146, 6],
       [1, 1, 1, 0, 4, 1.0, 4.605170185988092, 8],
       [1, 1, 0, 0, 4, 1.0, 6.173786103901937, 62],
       [1, 1, 0, 0, 4, 1.0, 4.857444178729352, 50],
       [1, 1, 0, 0, 4, 1.0, 4.875197323201151, 40],
       [1, 0, 0, 0, 1, 1.0, 5.043425116919247, 60],
       [1, 1, 1, 0, 5, 1.0, 4.812184355372417, 17],
       [0, 1, 2, 1, 4, 1.0, 4.584967478670572, 41],
       [1, 1, 0, 1, 4, 1.0, 4.700480365792417, 26],
       [0, 1, 0, 0, 4, 1.0, 4.727387818712341, 37],
       [1, 1, 0, 0, 4, 1.0, 4.736198448394496, 14],
       [1, 1, 1, 0, 4, 1.0, 5.521460917862246, 24],
       [1, 1, 1, 0, 2, 0.0, 5.075173815233827, 51],
       [0, 1, 2, 0, 4, 1.0, 4.844187086458591, 33],
       [0, 1, 2, 0, 4, 1.0, 5.117993812416755, 18],
       [1, 0, 0, 0, 4, 1.0, 4.976733742420574, 16],
       [1, 1, 0, 0, 3, 1.0, 5.1647859739235145, 64],
       [1, 0, 1, 1, 4, 1.0, 4.543294782270004, 10],
       [1, 1, 0, 1, 4, 1.0, 5.267858159063328, 25],
       [0, 0, 0, 0, 4, 1.0, 4.430816798843313, 12],
       [1, 1, 0, 0, 4, 1.0, 4.382026634673881, 9],
       [1, 0, 3, 0, 4, 1.0, 5.768320995793772, 43],
       [1, 1, 2, 0, 4, 1.0, 5.476463551931511, 66]], dtype=object)

In [42]:
Y_test

array([1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 0])

In [43]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
X_train=ss.fit_transform(X_train)
X_test=ss.fit_transform(X_test)

In [44]:
from sklearn.tree import DecisionTreeClassifier
DTClassifier= DecisionTreeClassifier(criterion='entropy',random_state=0)
DTClassifier.fit(X_train,Y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [45]:
Y_pred= DTClassifier.predict(X_test)
Y_pred

array([1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1])

In [46]:
from sklearn import metrics
print('The accuracy of decision tree is:',metrics.accuracy_score(Y_pred,Y_test))

The accuracy of decision tree is: 0.7101449275362319

In [47]:
from sklearn.naive_bayes import GaussianNB
NBClassifier = GaussianNB()
NBClassifier.fit(X_train,Y_train)

GaussianNB()

In [48]:
Y_pred= NBClassifier.predict(X_test)

In [49]:
Y_pred

array([1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1])

In [50]:
print('The accuracy of Naive Bayes is:',metrics.accuracy_score(Y_pred,Y_test))

The accuracy of Naive Bayes is: 0.7971014492753623

In [51]:
testdata= pd.read_csv('loan-test.csv')

In [52]:
testdata.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,LP001015,Male,Yes,0,Graduate,No,5720,0,110.0,360.0,1.0,Urban
1,LP001022,Male,Yes,1,Graduate,No,3076,1500,126.0,360.0,1.0,Urban
2,LP001031,Male,Yes,2,Graduate,No,5000,1800,208.0,360.0,1.0,Urban
3,LP001035,Male,Yes,2,Graduate,No,2340,2546,100.0,360.0,NaN,Urban
4,LP001051,Male,No,0,Not Graduate,No,3276,0,78.0,360.0,1.0,Urban

In [53]:
testdata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 367 entries, 0 to 366
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            367 non-null    object
 1   Gender             356 non-null    object
 2   Married            367 non-null    object
 3   Dependents         357 non-null    object
 4   Education          367 non-null    object
 5   Self_Employed      344 non-null    object
 6   ApplicantIncome    367 non-null    int64
 7   CoapplicantIncome  367 non-null    int64
 8   LoanAmount         362 non-null    float64
 9   Loan_Amount_Term   361 non-null    float64
 10  Credit_History     338 non-null    float64
 11  Property_Area      367 non-null    object
dtypes: float64(3), int64(2), object(7)
memory usage: 34.5+ KB

In [54]:
testdata.isnull().sum()

Loan_ID               0
Gender               11
Married               0
Dependents           10
Education             0
Self_Employed        23
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            5
Loan_Amount_Term      6
Credit_History       29
Property_Area         0
dtype: int64

In [55]:
testdata['Gender'].fillna(testdata['Gender'].mode()[0],inplace=True)
testdata['Dependents'].fillna(testdata['Dependents'].mode()[0],inplace=True)
testdata['Self_Employed'].fillna(testdata['Self_Employed'].mode()[0],inplace=True)
testdata['Loan_Amount_Term'].fillna(testdata['Loan_Amount_Term'].mode()[0],inplace=True)
testdata['Credit_History'].fillna(testdata['Credit_History'].mode()[0],inplace=True)

C:\Users\hp\AppData\Local\Temp\ipykernel_5060\2500130326.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  testdata['Gender'].fillna(testdata['Gender'].mode()[0],inplace=True)
C:\Users\hp\AppData\Local\Temp\ipykernel_5060\2500130326.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  testdata['Dependents'].fillna(testdata['Dependents'].mode()[0],inplace=True)
C:\Users\hp\AppData\Local\Temp\ipykernel_5060\2500130326.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  testdata['Self_Employed'].fillna(testdata['Self_Employed'].mode()[0],inplace=True)
C:\Users\hp\AppData\Local\Temp\ipykernel_5060\2500130326.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  testdata['Loan_Amount_Term'].fillna(testdata['Loan_Amount_Term'].mode()[0],inplace=True)
C:\Users\hp\AppData\Local\Temp\ipykernel_5060\2500130326.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  testdata['Credit_History'].fillna(testdata['Credit_History'].mode()[0],inplace=True)

In [56]:
testdata.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           5
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
dtype: int64

In [57]:
testdata.boxplot(column='LoanAmount')

In [58]:
testdata.LoanAmount= testdata.LoanAmount.fillna(testdata.LoanAmount.mean())

In [59]:
testdata['LoanAmount_log']=np.log(testdata['LoanAmount'])

In [60]:
testdata.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
LoanAmount_log       0
dtype: int64

In [61]:
testdata['TotalIncome']= testdata['ApplicantIncome']+testdata['CoapplicantIncome']
testdata['TotalIncome_log']= np.log(testdata['TotalIncome'])

In [62]:
testdata.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,LoanAmount_log,TotalIncome,TotalIncome_log
0,LP001015,Male,Yes,0,Graduate,No,5720,0,110.0,360.0,1.0,Urban,4.700480,5720,8.651724
1,LP001022,Male,Yes,1,Graduate,No,3076,1500,126.0,360.0,1.0,Urban,4.836282,4576,8.428581
2,LP001031,Male,Yes,2,Graduate,No,5000,1800,208.0,360.0,1.0,Urban,5.337538,6800,8.824678
3,LP001035,Male,Yes,2,Graduate,No,2340,2546,100.0,360.0,1.0,Urban,4.605170,4886,8.494129
4,LP001051,Male,No,0,Not Graduate,No,3276,0,78.0,360.0,1.0,Urban,4.356709,3276,8.094378

In [63]:
test= testdata.iloc[:,np.r_[1:5,9:11,13:15]].values

In [64]:
for i in range(0,5):
    X_test[:,i]= labelencoder_X.fit_transform(X_test[:,i])

In [65]:
test[:,7]= labelencoder_X.fit_transform(test[:,7])

In [66]:
test

array([['Male', 'Yes', '0', ..., 1.0, 5720, 207],
       ['Male', 'Yes', '1', ..., 1.0, 4576, 124],
       ['Male', 'Yes', '2', ..., 1.0, 6800, 251],
       ...,
       ['Male', 'No', '0', ..., 1.0, 5243, 174],
       ['Male', 'Yes', '0', ..., 1.0, 7393, 268],
       ['Male', 'No', '0', ..., 1.0, 9200, 311]], dtype=object)

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

ct = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['numeric_col1', 'numeric_col2']),
        ('cat', OneHotEncoder(), ['Gender', 'Category'])
    ]
)
test_transformed = ct.fit_transform(test)

In [15]:
pred = NBClassifier.Predict(test)

NameError: name 'NBClassifier' is not defined

In [16]:
pred

NameError: name 'pred' is not defined